[application]

name = "Editor"
default_platform = "desktop"
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "Editor"

# include `assets` in web platform
[web.resource]

[bundle]
identifier = "com.gabaudette.editor"
publisher = "gabaudette software"
resource = ["assets/*"]

# Additional CSS style files
style = [
    "assets/main.css",
    "assets/tailwind.css"
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
